namespace my_new.utils;

internal enum MYSYNC_EXITCODE
{
	TOO_LITTLE_PARAM = -10,
	SUCC = 0,
	GET_VER_ERROR = 1,
	GET_LIST_ERROR = 2,
	CHECKING_ERROR = 3,
	DOWNLOAD_ERROR = 4,
	PATCHING_ERROR = 5,
	CONFLICT_ERROR = 6,
	UNKNOW_ERROR = 7,
	TERMINATE_ERROR = 8,
	SUCC_AND_SELFUPDATE = 99
}
